Fix build
The build is currently failing during the installation of Jinja@2.6 with
an error like:

    File "..."
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'

It appears that Feature was a deprecated API that was removed,
reintroduced, and then removed again [0].

Bumping the minor version of the dependency to 2.7 fixes this issue. The
release notes for Jinja@2.7 are available here:
https://github.com/pallets/jinja/blob/2.7/CHANGES#L4

[0] https://github.com/pypa/setuptools/issues/2017#issuecomment-596307305

Change-Id: I9cdf088c3bef8fbcbbdf540a5022a2341aab111f